spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    password: 123456
    url: jdbc:mysql://localhost:3306/hisdb
    username: root
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true 